version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
      target: build
    volumes:
      - ./src/app:/go/reaction/src/app
    command: realize start --run --no-config
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: godockerDB
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
